In [1]:
import cvxpy as cvx
import numpy as np

In [ ]:
'''
Assuming that we get vector alpha1, alpha2, is first and we put n in the middle
'''
n = 6

alpha1 = np.array([[1,2,3,4,5,6,7,8],
                   [1,2,3,4,5,6,7,8]])
a1x = alpha1[0,:]
a2y = alpha1[1,:]

alpha2 = np.arange(10) + 15
alpha2 = alpha2[np.newaxis,:]
alpha2 = np.repeat(alpha2,2,axis=0)

a2x = alpha2[0,:]
a2y = alpha2[1,:]

Nf = n + len(a1x) + len(a2x)
assert Nf%2 == 0 , 'Nf must be odd'
cols = Nf//2
yhat = cvx.Variable(n)
xhat = cvx.Variable(n)
X = cvx.Variable(cols,cols)
Z = cvx.Variable(cols,cols)

totx = cvx.vstack(a1x,xhat,a2x)

#build hankel matrix
H = []
for i in range(cols):
    H.append([])
    for j in range(cols):
        H[i].append(totx[i+j])
H = cvx.bmat(H)

constr = [Z == Z.T, X == X.T, H >> 0]
obj = cvx.trace(X) + cvx.trace(Z)
p = cvx.Problem(cvx.Minimize(obj),constr)
p.solve()
            

In [8]:
Nf = 2
assert Nf%2 == 0 , 'Nf must be odd'

In [24]:
n = 6

alpha1 = np.array([[1,2,3,4,5,6,7,8],
                   [1,2,3,4,5,6,7,8]])
a1x = alpha1[0,:]
a2y = alpha1[1,:]

alpha2 = np.arange(10) + 15
alpha2 = alpha2[np.newaxis,:]
alpha2 = np.repeat(alpha2,2,axis=0)

a2x = alpha2[0,:]
a2y = alpha2[1,:]

xhat = cvx.Variable(n)

totx = cvx.vstack(a1x,xhat,a2x)
H = totx[0]
for i in range(cols):
    for j in range(cols):
        if i==0 and j== 0:
            continue
        if (i+j)>= len(alpha1) and (i+j) < len(alpha1) + n:
            

In [26]:
print(alpha1)
print(alpha2)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
[[15 16 17 18 19 20 21 22 23 24]
 [15 16 17 18 19 20 21 22 23 24]]
