In [25]:
# Solve a generalized assignment problem between the different tracklets 
# setting similarity weights on the assignments such that we maximize the
# total assignment weigthed objective and match the most likely tracklets
from gurobipy import *
from numpy import *
import os
import fnmatch

In [90]:
print cwd + '/3_obj_less_noisy'

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy


In [97]:
import fnmatch
import os
cwd = os.getcwd()
matches = []
for root, dirnames, filenames in os.walk(cwd + '/5_obj_obsolete'):
    for filename in fnmatch.filter(filenames, 'Pij_2.csv'):
        file_path = os.path.join(root, filename)
        P = loadtxt(open(root + '/' + filename, "rb"), delimiter=",")
#         if root == '/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_65':
        print root
        print P
        numT = shape(P)[0]
        try:
            numC = shape(P)[1]
        except:
            numC = 0;    

        print T
        print C
        T=range(numT)
        C=range(numC)

        # Initialize the model
        m=Model("Assignment")

        # Define the binary variables Xs
        X = []
        for t in T:
            X.append([])
            for c in C:
                X[t].append(m.addVar(vtype=GRB.BINARY,name="X%d%d"% (t, c)))

        # Set the optimization direction
        m.update()
        m.modelSense = GRB.MAXIMIZE


        # Define the assignment constraints
        constraintT = []
        constraintC = []

        # One variable assigned per column
        for t in range(numT):
            constraintT.append(m.addConstr(quicksum(X[t][c] for c in range(numC))
                                           <= 1 ,'constraintT%d' % t))

        # One variable assigned per row
        for c in range(numC):
            constraintT.append(m.addConstr(quicksum(X[t][c] for t in range(numT))
                                           <= 1 ,'constraintC%d' % t))


        # Define objective
        m.setObjective(quicksum(quicksum([X[t][c]*P[t][c] 
                                for c in range(numC)]) 
                                for t in range(numT)))

        m.update()

        # Solve the optimization problem
        m.optimize()

        # Print runtime and solution

        print 'runtime is',m.Runtime, 's'

        Xsol = zeros((numT,numC))
        # Print solution
        if m.status == GRB.Status.OPTIMAL:
            for t in range(numT):
                for c in range(numC):
                    if X[t][c].x > 0.5:
                        print('%g -> %g' % (t, c))
                        Xsol[t][c] = 1
        print Xsol
        name_sol = root + "/Assignment.csv"
        savetxt(name_sol, Xsol, delimiter=",")

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_65
[ -9.99530000e+02   1.88800000e-01   1.00000000e-02   1.18680000e-02]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective -0.000000000e+00
runtime is 0.0139338970184 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_66
[ -9.99290000e+02  -9.99290000e+02   1.46490000e-01   1.00000000e-02]
[0, 1, 2, 3]
[]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix ra

Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective -0.000000000e+00
runtime is 0.0174889564514 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_46
[[ -9.99580000e+02  -9.99580000e+02  -9.99580000e+02  -9.65360000e-02
   -6.69590000e-02]
 [ -9.99580000e+02  -9.99580000e+02  -9.99580000e+02   1.00000000e-02
    4.72340000e-02]]
[0, 1, 2, 3]
[]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range  

  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective -0.000000000e+00
runtime is 0.0170161724091 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_94
[ -9.99500000e+02  -9.99500000e+02   1.00000000e-02   2.39300000e-02]
[0, 1, 2, 3]
[]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 i

Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.057838

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.057838 

Optimal solution found (tolerance 1.00e-04)
Best objective 5.783800000000e-02, best bound 5.783800000000e-02, gap 0.0000%
runtime is 0.0216121673584 s
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_98
[ -9.99770000e+02  -9.99770000e+02  -9.99770000e+02   1.33340000e-01
   1.00000000e-02]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 5 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range  

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.39121
Presolve removed 8 rows and 12 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.89089 0.39121 

Optimal solution found (tolerance 1.00e-04)
Best objective 8.908900000000e-01, best bound 8.908900000000e-01, gap 0.0000%
runtime is 0.0301918983459 s
0 -> 1
1 -> 4
[[ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_42
[ -9.99600000e+02  -9.99600000e+02  -9.99600000e+02   1.00000000e-02]
[0, 1]
[0, 1, 2, 3, 4, 5]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  

  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.20561
Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.03 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.20561 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.205610000000e+00, best bound 1.205610000000e+00, gap 0.0000%
runtime is 0.0359170436859 s
0 -> 1
1 -> 2
[[ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_21
[[ -9.99700000e+02  -9.99700000e+02  -9.99700000e+02   1.75560000e-01
    9.47710000e-02   7.51820000e-03]
 [ -9.99700000e+02  -9.99700000e+02  -9.99700000e+02   1.50670000e-01
    1.21510000e-01   7.51820000e-03]
 [ -9.99700000e+02  -9.99700000e+02  -9.99700000e+02  -9.99700000e+02
    2.77910000e-02   1.00000000e-02]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 9 rows, 18 columns a

Variable types: 0 continuous, 8 integer (8 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0293531417847 s
1 -> 3
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_48
[ -9.99540000e+02   6.15640000e-02  -9.99540000e+02  -9.99540000e+02
   1.00000000e-02]
[0, 1]
[0, 1, 2, 3]
Optimize a model with 5 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolv

Thread count was 1 (of 8 available processors)

Solution count 1: 0.22176 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.217600000000e-01, best bound 2.217600000000e-01, gap 0.0000%
runtime is 0.0197241306305 s
0 -> 3
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_77
[[ -9.99620000e+02  -9.99620000e+02   1.68480000e-01   1.48590000e-01
   -1.35290000e-02]
 [ -9.99620000e+02  -9.99620000e+02   1.70630000e-01   2.23290000e-02
    1.00000000e-02]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.190809
Presolve removed 3 rows and 5 columns
Presolve time: 0.00s
Presolved: 4 rows, 5 columns, 9 nonzeros
Variable 

[0, 1, 2, 3, 4]
Optimize a model with 12 rows, 35 columns and 70 nonzeros
Variable types: 0 continuous, 35 integer (35 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.83033
Presolve removed 12 rows and 35 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 2.93822 1.83033 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.938220000000e+00, best bound 2.938220000000e+00, gap 0.0000%
runtime is 0.026083946228 s
0 -> 4
1 -> 5
4 -> 6
[[ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_69
[ -9.99730

Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective -0.000000000e+00
runtime is 0.0141949653625 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_63
[[ -9.99080000e+02   1.00000000e-02  -9.99080000e+02   4.52820000e-01
    1.55520000e-01]
 [ -9.99080000e+02  -9.99080000e+02  -9.99080000e+02  -9.99080000e+02
    3.88610000e-01]]
[0, 1, 2, 3]
[]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.39861
Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Ex

runtime is 0.026780128479 s
1 -> 3
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_87
[[ -9.98510000e+02  -9.98510000e+02  -1.24590000e-01]
 [ -9.98510000e+02  -9.98510000e+02   1.00000000e-02]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 5 rows, 6 columns and 12 nonzeros
Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0193071365356 s
1 -> 2
[[ 0.  0.  0.]
 [ 0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3

Variable types: 0 continuous, 28 integer (28 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.681359
Presolve removed 7 rows and 24 columns
Presolve time: 0.00s
Presolved: 4 rows, 4 columns, 8 nonzeros
Found heuristic solution: objective 2.7308800
Variable types: 0 continuous, 4 integer (4 binary)

Root relaxation: cutoff, 0 iterations, 0.00 seconds

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 2.73088 1.65298 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.730880000000e+00, best bound 2.730880000000e+00, gap 0.0000%
runtime is 0.0354478359222 s
0 -> 2
1 -> 4
2 -> 3
3 -> 5
[[ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization

Optimize a model with 10 rows, 25 columns and 50 nonzeros
Variable types: 0 continuous, 25 integer (25 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective -0

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: -0 

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%


runtime is 0.0195119380951 s
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_22
