In [25]:
# Solve a generalized assignment problem between the different tracklets 
# setting similarity weights on the assignments such that we maximize the
# total assignment weigthed objective and match the most likely tracklets
from gurobipy import *
from numpy import *
import os
import fnmatch

In [90]:
print cwd + '/3_obj_less_noisy'

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy


In [96]:
import fnmatch
import os
cwd = os.getcwd()
matches = []
for root, dirnames, filenames in os.walk(cwd + '/3_obj_less_noisy'):
    for filename in fnmatch.filter(filenames, 'Pij_2.csv'):
        file_path = os.path.join(root, filename)
        P = loadtxt(open(root + '/' + filename, "rb"), delimiter=",")
#         if root == '/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_65':
        print root
        print P
        numT = shape(P)[0]
        try:
            numC = shape(P)[1]
        except:
            numC = 0;    

        print T
        print C
        T=range(numT)
        C=range(numC)

        # Initialize the model
        m=Model("Assignment")

        # Define the binary variables Xs
        X = []
        for t in T:
            X.append([])
            for c in C:
                X[t].append(m.addVar(vtype=GRB.BINARY,name="X%d%d"% (t, c)))

        # Set the optimization direction
        m.update()
        m.modelSense = GRB.MAXIMIZE


        # Define the assignment constraints
        constraintT = []
        constraintC = []

        # One variable assigned per column
        for t in range(numT):
            constraintT.append(m.addConstr(quicksum(X[t][c] for c in range(numC))
                                           <= 1 ,'constraintT%d' % t))

        # One variable assigned per row
        for c in range(numC):
            constraintT.append(m.addConstr(quicksum(X[t][c] for t in range(numT))
                                           <= 1 ,'constraintC%d' % t))


        # Define objective
        m.setObjective(quicksum(quicksum([X[t][c]*P[t][c] 
                                for c in range(numC)]) 
                                for t in range(numT)))

        m.update()

        # Solve the optimization problem
        m.optimize()

        # Print runtime and solution

        print 'runtime is',m.Runtime, 's'

        Xsol = zeros((numT,numC))
        # Print solution
        if m.status == GRB.Status.OPTIMAL:
            for t in range(numT):
                for c in range(numC):
                    if X[t][c].x > 0.5:
                        print('%g -> %g' % (t, c))
                        Xsol[t][c] = 1
        print Xsol
        name_sol = root + "/Assignment.csv"
        savetxt(name_sol, Xsol, delimiter=",")

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_65
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -1.09860000e+00
    7.80000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   6.96670000e-01
   -1.16190000e+00]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [7e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.47667

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.47667 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.476670000000e+00, best bound 1.476670000000e+00, gap 0.0000%
runtime is 0.0239861011505 s
0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimizati


Solved in 0 iterations and 0.01 seconds
Optimal objective -0.000000000e+00
runtime is 0.0151338577271 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_41
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   1.03000000e+00
   -8.98570000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -8.55710000e-01
    6.13330000e-01]]
[0, 1, 2, 3]
[]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.64333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.64333 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.643330000000e+00, best bound 1.643330000000e+00, gap 0.0000%
runtime is 0.0201730728149 s
0 ->

Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01
Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 1.5555 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.555500000000e+00, best bound 1.555500000000e+00, gap 0.0000%
runtime is 0.0253999233246 s
0 -> 4
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_79
[ -1.00130000e+03  -1.00130000e+03  -1.00130000e+03   1.00000000e-02]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Obje

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.39333 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.393330000000e+00, best bound 1.393330000000e+00, gap 0.0000%
runtime is 0.0201771259308 s
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_38
[ -1.00070000e+03  -1.00070000e+03  -1.00070000e+03   1.00000000e-02]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve tim

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective -0.000000000e+00
runtime is 0.0158739089966 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_27
[ -1.00030000e+03  -1.00030000e+03  -1.00030000e+03   1.00000000e-02]
[0, 1, 2, 3]
[]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.02 seconds
Optimal objective -0.000000000e+00
runtime is 0.0200190544128 s
[]
/home/david/Dropbox/Ubuntu/Convex_Op

  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.02 seconds
Optimal objective -0.000000000e+00
runtime is 0.0192220211029 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_21
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -5.41430000e-01
    3.63330000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   1.28000000e+00
   -3.03330000e-01]]
[0, 1, 2, 3]
[]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Foun

Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.86 0.33429 

Optimal solution found (tolerance 1.00e-04)
Best objective 8.600000000000e-01, best bound 8.600000000000e-01, gap 0.0000%
runtime is 0.024708032608 s
0 -> 4
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_48
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -5.70000000e-01
    2.80000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   1.53000000e+00
   -1.36670000e-01]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00,


Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.97667 

Optimal solution found (tolerance 1.00e-04)
Best objective 9.766700000000e-01, best bound 9.766700000000e-01, gap 0.0000%
runtime is 0.0150189399719 s
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_53
[[ -9.99280000e+02  -9.99280000e+02  -9.99280000e+02   1.00000000e-02
    1.99330000e+00]
 [ -9.99280000e+02  -9.99280000e+02  -9.99280000e+02  -9.99280000e+02
    5.76190000e-02]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.067619
Presolve removed 7 rows and 10 columns
Pres

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_1
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   5.30000000e-01
   -1.36670000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -1.70000000e-01
    7.80000000e-01]]
[0, 1, 2]
[0, 1, 2, 3, 4, 5]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.31

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.31 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.310000000000e+00, best bound 1.310000000000e+00, gap 0.0000%
runtime is 0.0240440368652 s
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimizatio

runtime is 0.0215709209442 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_86
[ -1.00080000e+03  -1.00080000e+03  -1.00080000e+03   1.00000000e-02]
[0, 1, 2, 3]
[]
Optimize a model with 4 rows, 0 columns and 0 nonzeros
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 4 rows and 0 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.02 seconds
Optimal objective -0.000000000e+00
runtime is 0.0193560123444 s
[]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_40
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -5.98570000e-01
    6.96670000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   3.

Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.78

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.78 

Optimal solution found (tolerance 1.00e-04)
Best objective 7.800000000000e-01, best bound 7.800000000000e-01, gap 0.0000%
runtime is 0.0145659446716 s
1 -> 4
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_58
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -3.70000000e-01
    2.80000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   3.63330000e-01
   -2.20000000e-01]]
[0, 1]
[0, 1, 2, 3, 4]
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coef

Optimize a model with 10 rows, 25 columns and 50 nonzeros
Variable types: 0 continuous, 25 integer (25 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective -0

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: -0 

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%


runtime is 0.0195119380951 s
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_22
