In [25]:
# Solve a generalized assignment problem between the different tracklets 
# setting similarity weights on the assignments such that we maximize the
# total assignment weigthed objective and match the most likely tracklets
from gurobipy import *
from numpy import *
import os
import fnmatch

In [90]:
print cwd + '/3_obj_less_noisy'

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy


In [150]:
import fnmatch
import os
cwd = os.getcwd()
matches = []
for root, dirnames, filenames in os.walk(cwd):
    for filename in fnmatch.filter(filenames, 'Pij_2.csv'):
        file_path = os.path.join(root, filename)
        P = loadtxt(open(root + '/' + filename, "rb"), delimiter=",")
#         if root == '/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_1':
        print root
        print P
        numT = shape(P)[0]
        try:
            numC = shape(P)[1]
        except:
            numC = 0;    

        print numC
        T=range(numT)
        C=range(numC)

        # Initialize the model
        m=Model("Assignment")

        # Define the binary variables Xs
        X = []
        for t in T:
            X.append([])
            if numC != 0:
                for c in C:
                    X[t].append(m.addVar(vtype=GRB.BINARY,name="X%d%d"% (t, c)))
            else:
                X[t].append(m.addVar(vtype=GRB.BINARY,name="X%d%d"% (t, 0)))

        # Set the optimization direction
        m.update()
        m.modelSense = GRB.MAXIMIZE


        # Define the assignment constraints
        constraintT = []
        constraintC = []


        if numC != 0:
            # One variable assigned per column
            for t in range(numT):
                constraintT.append(m.addConstr(quicksum(X[t][c] for c in range(numC))
                                               <= 1 ,'constraintT%d' % t))
            # One variable assigned per row
            for c in range(numC):
                constraintT.append(m.addConstr(quicksum(X[t][c] for t in range(numT))
                                               <= 1 ,'constraintC%d' % t))

            # Define objective
            m.setObjective(quicksum(quicksum([X[t][c]*P[t][c] 
                                    for c in range(numC)]) 
                                    for t in range(numT)))
        else:
            # One variable assigned per column
            for t in range(numT):
                constraintT.append(m.addConstr(X[t][0]<= 1 ,'constraintT%d' % t))  

            # One variable assigned per row
            constraintT.append(m.addConstr(quicksum(X[t][0] for t in range(numT))
                                               <= 1 ,'constraintC%d' % t))

            # Define objective                 
            m.setObjective(quicksum(X[t][0]*P[t] for t in range(numT)))



        m.update()

        # Solve the optimization problem
        m.optimize()

        # Print runtime and solution

        print 'runtime is',m.Runtime, 's'
        print m


        if numC != 0:
            Xsol = zeros((numT,numC))
        else:
            Xsol = zeros(numT)
        # Print solution
        if m.status == GRB.Status.OPTIMAL:
            for t in range(numT):
                if numC != 0:
                    for c in range(numC):
                        if X[t][c].x > 0.5:
                            print('%g -> %g' % (t, c))
                            Xsol[t][c] = 1
                else:
                    if X[t][0].x > 0.5:
                        print('0 -> %g' % (t))
                        Xsol[t] = 1
        print Xsol
        name_sol = root + "/Assignment.csv"
        if numC != 0:
            savetxt(name_sol, Xsol, delimiter=",")
        else:
            savetxt(name_sol, Xsol[None], delimiter=",")
        

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_59
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -9.03330000e-01   1.36330000e+00]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02   3.63330000e-01  -9.03330000e-01]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.72663

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.72663 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.726630000000e+00, best bound 1.726630000000e+00, gap 0.0000%
runtime is 0.0180711746216 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars,

Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.06

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.06 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.060000000000e+00, best bound 1.060000000000e+00, gap 0.0000%
runtime is 0.0175259113312 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
1 -> 5
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_33
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -5.70000000e-01   8.63330000e-01  -1.43670000e+00]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9

Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [5e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.69667

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.69667 

Optimal solution found (tolerance 1.00e-04)
Best objective 6.966700000000e-01, best bound 6.966700000000e-01, gap 0.0000%
runtime is 0.0170738697052 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_69
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -3.45000000e-01   1.03000000e+00]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0162651538849 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[ 0.  0.  0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_64
[[-999.99   -999.99   -999.99   -999.99   -999.99      1.03     -1.3064]
 [-999.99   -999.99   -999.99   -999.99   -999.99   -999.99      1.03  ]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix ran

Variable types: 0 continuous, 21 integer (21 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.72

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.72 

Optimal solution found (tolerance 1.00e-04)
Best objective 7.200000000000e-01, best bound 7.200000000000e-01, gap 0.0000%
runtime is 0.0182719230652 s
<gurobi.Model MIP instance Assignment: 10 constrs, 21 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
1 -> 6
[[ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_15
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -3.98570000e-01  -3.98570000e-01   1.53000000e+00]
 [ -9.99990000e+02  -9.9

2 -> 7
3 -> 8
[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_56
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -7.31900000e-01   3.63330000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02   1.03000000e+00  -9.03330000e-01]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 1.39333 

Optimal solution found (tolerance 1.00

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_55
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -6.20000000e-01
   -9.99990000e+02  -9.99990000e+02   3.63330000e-01  -1.29730000e+00
   -1.31130000e+00]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   1.03000000e+00
   -9.99990000e+02  -9.99990000e+02  -8.80710000e-01   1.13330000e-01
   -1.23140000e+00]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -1.32900000e+00
    1.36330000e+00]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   1.03000000e+00
   -7.41430000e-01]]
9
Optimize a model with 13 rows, 36 columns and 72 nonzeros
Variable types: 0 continuous, 36 integer (36 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 

   7.60000000e-01   1.00000000e-02]
0
Optimize a model with 7 rows, 6 columns and 12 nonzeros
Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.76
Presolve removed 7 rows and 6 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.76 

Optimal solution found (tolerance 1.00e-04)
Best objective 7.600000000000e-01, best bound 7.600000000000e-01, gap 0.0000%
runtime is 0.0289721488953 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
[ 0.  0.  0.  0.  1.  0.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_30
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02

Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.39333 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.933300000000e-01, best bound 3.933300000000e-01, gap 0.0000%
runtime is 0.0201539993286 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
1 -> 6
[[ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_82
[ -1.00130000e+03  -1.00130000e+03  -1.00130000e+03  -1.00130000e+03
  -1.00130000e+03   1.00000000e-02]
0
Optimize a model with 7 rows, 6 columns and 12 nonzeros
Variable types: 0 continuous


Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0139360427856 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[ 0.  0.  0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_38
[ -1.00030000e+03  -1.00030000e+03  -1.00030000e+03  -1.00030000e+03
  -1.00030000e+03   1.00000000e-02]
0
Optimize a model with 7 rows, 6 columns and 12 nonzeros
Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8

  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 2.79004
Presolve removed 13 rows and 36 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 3.28004 2.79004 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.280040000000e+00, best bound 3.280040000000e+00, gap 0.0000%
runtime is 0.0222940444946 s
<gurobi.Model MIP instance Assignment: 13 constrs, 36 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
2 -> 7
3 -> 8
[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_20
[ -1.00030000e+03  -1.00030000e+03  -1.00030000e+03  -1.00

runtime is 0.0236239433289 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[ 0.  0.  0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_97
[[ -9.99810000e+02  -9.99810000e+02  -9.99810000e+02  -9.99810000e+02
   -9.99810000e+02   4.76670000e-01  -6.02500000e-01  -1.14560000e+00]
 [ -9.99810000e+02  -9.99810000e+02  -9.99810000e+02  -9.99810000e+02
   -9.99810000e+02  -9.99810000e+02  -5.51900000e-01   1.00000000e-02]
 [ -9.99810000e+02  -9.99810000e+02  -9.99810000e+02  -9.99810000e+02
   -9.99810000e+02  -9.99810000e+02   5.43330000e-01  -6.23330000e-01]]
8
Optimize a model with 11 rows, 24 columns and 48 nonzeros
Variable types: 0 continuous, 24 integer (24 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.03

Explored 

  Objective range  [1e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.64333

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.64333 

Optimal solution found (tolerance 1.00e-04)
Best objective 6.433300000000e-01, best bound 6.433300000000e-01, gap 0.0000%
runtime is 0.0224320888519 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
1 -> 5
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_78
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02  -1.12560000e+00   6.96670000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -9.99990000e+02
   -9.99990000e+02   1.03000000e+00  -1.10640000e+00]]
7
Optimize a model with 9 rows, 14 columns and 28 non

  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.72666

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.72666 

Optimal solution found (tolerance 1.00e-04)
Best objective 7.266600000000e-01, best bound 7.266600000000e-01, gap 0.0000%
runtime is 0.0199828147888 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
1 -> 5
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj_less_noisy/csv_5_16
[[ -9.99760000e+02  -9.99760000e+02   2.26000000e+00  -9.99760000e+02
   -9.99760000e+02  -9.99760000e+02  -7.85450000e-01]
 [ -9.99760000e+02  -9.99760000e+02  -8.65000000e-01  -9.99760000e+02
   -9.99760000e+02  -9.99760000e+02   1.00000000e-02]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficie

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_99
[[ -9.99610000e+02  -9.99610000e+02  -9.99610000e+02  -9.99610000e+02
   -9.99610000e+02  -1.00890000e+00]
 [ -9.99610000e+02  -9.99610000e+02  -9.99610000e+02  -9.99610000e+02
    1.17930000e-01  -8.74350000e-02]
 [ -9.99610000e+02  -9.99610000e+02  -9.99610000e+02  -9.99610000e+02
   -9.99610000e+02   1.00000000e-02]]
6
Optimize a model with 9 rows, 18 columns and 36 nonzeros
Variable types: 0 continuous, 18 integer (18 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.12793

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.12793 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.279300000000e-01, best bound 1.279300000000e-01, gap 0.0000%
runtime is 0.026544094085

Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.12788 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.278800000000e-01, best bound 1.278800000000e-01, gap 0.0000%
runtime is 0.0216591358185 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_32
[[ -9.99680000e+02  -9.99680000e+02  -9.99680000e+02   1.00000000e-02
    2.81820000e-02]
 [ -9.99680000e+02  -9.99680000e+02  -9.99680000e+02  -6.92260000e-02
   -2.56670000e-01]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02

Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0221259593964 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
1 -> 4
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_19
[[ -9.99360000e+02  -9.99360000e+02  -9.99360000e+02  -9.99360000e+02
   -9.99360000e+02]
 [ -9.99360000e+02  -9.99360000e+02  -9.99360000e+02  -9.99360000e+02
    1.00000000e-02]]
5
Optimize a model with 7 rows, 10 columns and 20 

Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0131721496582 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
1 -> 4
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_91
[[ -9.99710000e+02  -9.99710000e+02  -9.99710000e+02  -2.03670000e-02
    1.00000000e-02]
 [ -9.99710000e+02  -9.99710000e+02  -9.99710000e+02   4.93260000e-02
    1.00000000e-02]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.059326
Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Threa

runtime is 0.0227501392365 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_90
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   3.63330000e-01
   -5.70000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -3.70000000e-01
    3.00000000e-02]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.39333 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.933300000000e-01, best bound

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.031696
Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 2.7995 0.031696 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.799500000000e+00, best bound 2.799500000000e+00, gap 0.0000%
runtime is 0.0192880630493 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_99
[ -1.00200000e+03  -1.00200000e+03  -1.00200000e+03   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_94
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -4.22380000e-01
    3.00000000e-02]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   5.30000000e-01
   -6.20000000e-01]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.56

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.56 

Optimal solution found (tolerance 1.00e-04)
Best objective 5.600000000000e-01, best bound 5.600000000000e-01, gap 0.0000%
runtime is 0.0255889892578 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_38
[ -1.00070000e+03  -1.00070000e+03  -1.00070000e+03   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0205562114716 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_98
[ -1.00080000e+03  -1.00080000e+

<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_73
[ -1.00030000e+03  -1.00030000e+03  -1.00030000e+03   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0177688598633 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/ho

Thread count was 1 (of 8 available processors)

Solution count 1: 1.72663 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.726630000000e+00, best bound 1.726630000000e+00, gap 0.0000%
runtime is 0.0168249607086 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_49
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   8.63330000e-01
   -8.45000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -6.36670000e-01
    1.03000000e+00]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 1.89333

Explored 0 nodes (0 sim

0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_88
[ -1.00130000e+03  -1.00130000e+03  -1.00130000e+03   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0202021598816 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experimen

    3.00000000e-02]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.39333 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.933300000000e-01, best bound 3.933300000000e-01, gap 0.0000%
runtime is 0.0218670368195 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
1 -> 4
[[ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_15
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   8.63330000e-01
   -5.70000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  

Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 2.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 2.39333 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.393330000000e+00, best bound 2.393330000000e+00, gap 0.0000%
runtime is 0.0200369358063 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_50
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -8.58890000e-01
    2.80000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   3.63330000e-01
   -9.70000000e-01]]
5
Optimize a model with 7 

Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.72666

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.72666 

Optimal solution found (tolerance 1.00e-04)
Best objective 7.266600000000e-01, best bound 7.266600000000e-01, gap 0.0000%
runtime is 0.0247609615326 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_35
[ -1.00030000e+03  -1.00030000e+03  -1.00030000e+03   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Mat

runtime is 0.0173420906067 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_less_noisy/csv_3_87
[[ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02   3.63330000e-01
   -9.70000000e-01]
 [ -9.99990000e+02  -9.99990000e+02  -9.99990000e+02  -1.23670000e+00
    3.00000000e-02]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.39333

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.39333 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.933300000000e-01, best bound 3.933300000000e-01, gap 0.0000%
runt

5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [4e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 2.1433

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 2.1433 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.143300000000e+00, best bound 2.143300000000e+00, gap 0.0000%
runtime is 0.0122740268707 s
<gurobi.Model MIP instance Assignment: 7 constrs, 10 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
1 -> 3
[[ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_65
[ -9.99530000e+02   1.88800000e-01   1.00000000e-02   1.18680000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continu

Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01
Presolve removed 5 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.044629 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 4.462900000000e-02, best bound 4.462900000000e-02, gap 0.0000%
runtime is 0.0238621234894 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_41
[[ -9.99500000e+02  -9.99500000e+02   2.31880000e-01   1.76990000e-02
    1.00000000e-02]
 [ -9.99500000e+02  -9.99500000e+02  -9.99500000e+02  -2.

  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.206145
Presolve removed 10 rows and 21 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.30738 0.206145 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.073800000000e-01, best bound 3.073800000000e-01, gap 0.0000%
runtime is 0.0195038318634 s
<gurobi.Model MIP instance Assignment: 10 constrs, 21 vars, Parameter changes: LogFile=gurobi.log>
2 -> 5
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_76
[ -9.99640000e+02  -9.99640000e+02   1.00000000e-02   4.71370000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable

Best objective 1.769270000000e+00, best bound 1.769270000000e+00, gap 0.0000%
runtime is 0.0350971221924 s
<gurobi.Model MIP instance Assignment: 11 constrs, 28 vars, Parameter changes: LogFile=gurobi.log>
0 -> 2
2 -> 3
3 -> 6
[[ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_89
[ -9.99630000e+02  -9.99630000e+02   2.23580000e-01   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.22358
Presolve removed 5 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (


Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.19584 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.958400000000e-01, best bound 1.958400000000e-01, gap 0.0000%
runtime is 0.0227952003479 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 1
[ 0.  1.  0.  0.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_44
[ -9.99550000e+02  -9.99550000e+02   1.00000000e-02   8.67750000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01
Presolve removed 5 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simpl

runtime is 0.0178949832916 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_43
[[ -9.99210000e+02  -9.99210000e+02   3.54250000e-01  -8.04080000e-01
   -6.58250000e-01  -8.15510000e-01   1.04450000e-01]
 [ -9.99210000e+02  -9.99210000e+02  -9.99210000e+02   1.12770000e-01
    8.02370000e-03   1.00000000e-02  -9.99210000e+02]
 [ -9.99210000e+02  -9.99210000e+02  -9.99210000e+02   3.09820000e-01
   -1.04620000e-01  -1.98420000e-02  -9.99210000e+02]
 [ -9.99210000e+02  -9.99210000e+02  -9.99210000e+02  -9.99210000e+02
    7.50860000e-02  -9.99210000e+02  -9.99210000e+02]]
7
Optimize a model with 11 rows, 28 columns and 56 nonzeros
Variable types: 0 continuous, 28 integer (28 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-03, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e

    2.77910000e-02   1.00000000e-02]]
6
Optimize a model with 9 rows, 18 columns and 36 nonzeros
Variable types: 0 continuous, 18 integer (18 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [8e-03, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.30707
Presolve removed 9 rows and 18 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.30707 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.070700000000e-01, best bound 3.070700000000e-01, gap 0.0000%
runtime is 0.0272068977356 s
<gurobi.Model MIP instance Assignment: 9 constrs, 18 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
1 -> 4
2 -> 5
[[ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experim


Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 3.64082 3.47382 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.640820000000e+00, best bound 3.640820000000e+00, gap 0.0000%
runtime is 0.0429630279541 s
<gurobi.Model MIP instance Assignment: 13 constrs, 40 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
1 -> 2
2 -> 5
3 -> 7
4 -> 6
[[ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_30
[[ -9.99760000e+02  -9.99760000e+02  -9.99760000e+02  -8.52910000e-02]
 [ -9.99760000e+02  -9.99760000e+02  -9.99760000e+02   1.00000000e-02]]
4
Optimize a model with 6 rows, 8 columns and 16 nonzeros
Variable types: 0 continuous, 8 integer (8 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+0

Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.035847
Presolve removed 5 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.035847 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.584700000000e-02, best bound 3.584700000000e-02, gap 0.0000%
runtime is 0.0205020904541 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 2
[ 0.  0.  1.  0.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_23
[[ -9.99590000e+02  -9.99590000e+02  -9.99590000e+02   2.21760000e-01
    1.00000000e-02]
 [ -9.99590000e+02  -9.99590000e+02  -9.99590000e+02   1.9

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_4
[[ -9.99460000e+02  -9.99460000e+02  -9.99460000e+02  -1.64870000e-01
    1.26030000e-01]
 [ -9.99460000e+02  -9.99460000e+02  -9.99460000e+02   1.00000000e-02
    1.33420000e-01]]
5
Optimize a model with 7 rows, 10 columns and 20 nonzeros
Variable types: 0 continuous, 10 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.13603
Presolve removed 7 rows and 10 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.13603 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.360300000000e-01, best bound 1.360300000000e-01, gap 0.0000%
runtime is 0.0185761451721 s
<gurobi.Model MIP instance Ass


Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 3.24112 2.59052 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.241120000000e+00, best bound 3.241120000000e+00, gap 0.0000%
runtime is 0.045511007309 s
<gurobi.Model MIP instance Assignment: 11 constrs, 28 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
1 -> 2
2 -> 6
3 -> 5
[[ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_93
[[ -9.99210000e+02  -9.99210000e+02  -3.61430000e-01  -9.99210000e+02
    6.07320000e-01   4.36190000e-01]
 [ -9.99210000e+02  -9.99210000e+02   1.00000000e-02  -9.99210000e+02
    5.55100000e-01   3.34240000e-01]]
6
Optimize a model with 8 rows, 12 columns and 24 nonzeros
Variable types: 0 continuous, 12 integer (12 binary)
Coefficient statistics:
  Matrix range 

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01
Presolve removed 5 rows and 4 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.11417 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.141700000000e-01, best bound 1.141700000000e-01, gap 0.0000%
runtime is 0.0220091342926 s
<gurobi.Model MIP instance Assignment: 5 constrs, 4 vars, Parameter changes: LogFile=gurobi.log>
0 -> 3
[ 0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_40
[ -9.99640000e+02   7.04010000e-02   5.47300000e-02   1.00000000e-02]
0
Optimize a model with 5 rows, 4 columns and 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)
Coefficient statistic

Variable types: 0 continuous, 4 integer (4 binary)

Root relaxation: objective 6.408750e-01, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0       0.6408750    0.64087  0.00%     -    0s

Explored 0 nodes (1 simplex iterations) in 0.03 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 0.640875 0.628521 

Optimal solution found (tolerance 1.00e-04)
Best objective 6.408750000000e-01, best bound 6.408750000000e-01, gap 0.0000%
runtime is 0.0404078960419 s
<gurobi.Model MIP instance Assignment: 11 constrs, 28 vars, Parameter changes: LogFile=gurobi.log>
0 -> 4
1 -> 3
2 -> 6
3 -> 5
[[ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj_obsolete/csv_3_0
[[ -9.99330000e+0

/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_59
[[ -9.99580000e+02  -9.99580000e+02  -2.67260000e-01  -9.99580000e+02
   -9.99580000e+02  -9.99580000e+02   1.76180000e-01  -6.26320000e-01
   -6.53670000e-01]
 [ -9.99580000e+02  -9.99580000e+02   1.54630000e-01  -9.99580000e+02
   -9.99580000e+02  -9.99580000e+02   9.66450000e-02  -4.62430000e-01
   -7.13410000e-01]
 [ -9.99580000e+02  -9.99580000e+02  -9.99580000e+02  -9.99580000e+02
   -9.99580000e+02  -9.99580000e+02  -9.99580000e+02   1.00000000e-02
   -2.89350000e-01]
 [ -9.99580000e+02  -9.99580000e+02  -9.99580000e+02  -9.99580000e+02
   -9.99580000e+02  -9.99580000e+02  -9.99580000e+02  -9.99580000e+02
    2.10400000e-02]]
9
Optimize a model with 13 rows, 36 columns and 72 nonzeros
Variable types: 0 continuous, 36 integer (36 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Foun

   -9.99510000e+02  -5.22010000e-02   1.09430000e-01]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.11943
Presolve removed 9 rows and 14 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.11943 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.194300000000e-01, best bound 1.194300000000e-01, gap 0.0000%
runtime is 0.0257699489594 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
1 -> 6
[[ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_ob

Best objective 3.633100000000e+00, best bound 3.633100000000e+00, gap 0.0000%
runtime is 0.0345809459686 s
<gurobi.Model MIP instance Assignment: 12 constrs, 27 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
1 -> 8
2 -> 7
[[ 0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_17
[[ -9.99680000e+02  -9.99680000e+02  -9.99680000e+02  -9.99680000e+02
   -9.99680000e+02  -9.99680000e+02  -2.49500000e-02   1.00000000e-02]
 [ -9.99680000e+02  -9.99680000e+02  -9.99680000e+02  -9.99680000e+02
   -9.99680000e+02  -9.99680000e+02   1.58620000e-01  -2.18010000e-01]
 [ -9.99680000e+02  -9.99680000e+02  -9.99680000e+02  -9.99680000e+02
   -9.99680000e+02  -9.99680000e+02   1.44270000e-02  -4.17080000e-02]]
8
Optimize a model with 11 rows, 24 columns and 48 nonzeros
Variable types: 0 continuous, 24 integer (24 binary)
Coefficient statistics:
  Matrix ran

runtime is 0.0141031742096 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
1 -> 6
[[ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_83
[[ -9.99360000e+02  -9.99360000e+02  -9.99360000e+02  -9.99360000e+02
   -9.99360000e+02  -1.93870000e-02   1.43300000e-01]
 [ -9.99360000e+02  -9.99360000e+02  -9.99360000e+02  -9.99360000e+02
   -9.99360000e+02   1.00000000e-02   9.89610000e-02]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.1533
Presolve removed 9 rows and 14 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 se

Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01
Presolve removed 9 rows and 14 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.014762 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.476200000000e-02, best bound 1.476200000000e-02, gap 0.0000%
runtime is 0.0170021057129 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
1 -> 6
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_50
[ -9.99710000e+02  -9.99710000e+02  -9.99710000e+02  -9.99710000e+02
  -9.99710000e+02   1.00000000e-02]
0


Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0159409046173 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[ 0.  0.  0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_46
[[ -9.99500000e+02  -9.99500000e+02  -9.99500000e+02  -9.99500000e+02
   -9.99500000e+02   1.79200000e-01   1.00000000e-02]
 [ -9.99500000e+02  -9.99500000e+02  -9.99500000e+02  -9.99500000e+02
   -9.99500000e+02   1.76440000e-01  -1.33960000e-01]]
7
Opti

Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0222358703613 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[ 0.  0.  0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_92
[ -9.99610000e+02  -9.99610000e+02  -9.99610000e+02  -9.99610000e+02
   1.99150000e-01   1.00000000e-02]
0
Optimize a model with 7 rows, 6 columns and 12 nonzeros
Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range   


Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.043333 

Optimal solution found (tolerance 1.00e-04)
Best objective 4.333300000000e-02, best bound 4.333300000000e-02, gap 0.0000%
runtime is 0.0231659412384 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[[ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_19
[[ -9.99340000e+02  -9.99340000e+02  -9.99340000e+02  -5.23330000e-01
   -9.99340000e+02  -9.99340000e+02   4.79840000e-01   1.88100000e-01
    1.95160000e-01]
 [ -9.99340000e+02  -9.99340000e+02  -9.99340000e+02   1.00000000e-02
   -9.99340000e+02  -9.99340000e+02   4.54440000e-01   2.35490000e-01
    2.17210000e-01]
 [ -9.99340000e+02  -9.99340000e+02  -9.99340000e+02  -9.99340000e+02
   -9.99340000e+02  -9.99340000e+02  -9.99340000e+02   3.50090000e-01
    4

Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.032364
Presolve removed 9 rows and 14 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.02 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.032364 

Optimal solution found (tolerance 1.00e-04)
Best objective 3.236400000000e-02, best bound 3.236400000000e-02, gap 0.0000%
runtime is 0.0280511379242 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
1 -> 5
[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_12
[[ -9.99300000e+02  -9.99300000e+02  -9.99300000e+02  -4.51380000e-02
    1.00250000e-04   2.68150000e-01  -9.99300000e+02  -9.99300000e+02
    3.37070000e-01  -

  Matrix range     [1e+00, 1e+00]
  Objective range  [3e-05, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01
Presolve removed 9 rows and 14 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 2: 0.060357 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 6.035700000000e-02, best bound 6.035700000000e-02, gap 0.0000%
runtime is 0.0221040248871 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_26
[ -9.99840000e+02  -9.99840000e+02  -9.99840000e+02   1.49640000e-01
   2.11110000e-02   1.00000000e-02]
0
Optimize a model with 7 rows, 6 columns and 12 nonzeros
Variable types: 0 con

Best objective 8.244500000000e-02, best bound 8.244500000000e-02, gap 0.0000%
runtime is 0.0166761875153 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
1 -> 5
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_95
[[ -9.99590000e+02  -9.99590000e+02  -9.99590000e+02  -9.99590000e+02
   -9.99590000e+02  -8.76660000e-03   9.23600000e-02]
 [ -9.99590000e+02  -9.99590000e+02  -9.99590000e+02  -9.99590000e+02
   -9.99590000e+02   1.00000000e-02  -2.49210000e-02]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [9e-03, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.10236

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count w

    4.19650000e-02]]
9
Optimize a model with 13 rows, 36 columns and 72 nonzeros
Variable types: 0 continuous, 36 integer (36 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.193799
Presolve removed 9 rows and 32 columns
Presolve time: 0.00s
Presolved: 4 rows, 4 columns, 8 nonzeros
Variable types: 0 continuous, 4 integer (4 binary)

Root relaxation: objective 2.035280e-01, 1 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0       0.2035280    0.20353  0.00%     -    0s

Explored 0 nodes (1 simplex iterations) in 0.04 seconds
Thread count was 8 (of 8 available processors)

Solution count 2: 0.203528 0.193799 

Optimal solution found (tolerance 1.00e-04)
Best objective 2.035280000

Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.01

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0.01 

Optimal solution found (tolerance 1.00e-04)
Best objective 1.000000000000e-02, best bound 1.000000000000e-02, gap 0.0000%
runtime is 0.0219030380249 s
<gurobi.Model MIP instance Assignment: 7 constrs, 6 vars, Parameter changes: LogFile=gurobi.log>
0 -> 5
[ 0.  0.  0.  0.  0.  1.]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_99
[ -9.99760000e+02  -9.99760000e+02  -9.99760000e+02  -9.99760000e+02
   1.00000000e-02   7.00370000e-02]
0
Optimize a model with 7 rows, 6 columns and 12 nonzeros
Variable types: 0 continuous, 6 integer (6 binary)
Coefficient statistics:
  Matrix range   

Best objective 8.809300000000e-02, best bound 8.809300000000e-02, gap 0.0000%
runtime is 0.0127010345459 s
<gurobi.Model MIP instance Assignment: 9 constrs, 14 vars, Parameter changes: LogFile=gurobi.log>
0 -> 6
1 -> 5
[[ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/5_obj/csv_5_18
[[ -9.99540000e+02  -9.99540000e+02  -9.99540000e+02  -9.99540000e+02
   -9.99540000e+02   1.00000000e-02   2.34320000e-01]
 [ -9.99540000e+02  -9.99540000e+02  -9.99540000e+02  -9.99540000e+02
   -9.99540000e+02  -9.99540000e+02   4.44330000e-02]]
7
Optimize a model with 9 rows, 14 columns and 28 nonzeros
Variable types: 0 continuous, 14 integer (14 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [1e-02, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective 0.054433
Presolve removed 9 rows and 14 columns
Presolve time: 0.00s
Presolve: 

Optimize a model with 10 rows, 25 columns and 50 nonzeros
Variable types: 0 continuous, 25 integer (25 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [6e-01, 1e+03]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Found heuristic solution: objective -0

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: -0 

Optimal solution found (tolerance 1.00e-04)
Best objective -0.000000000000e+00, best bound -0.000000000000e+00, gap 0.0000%


runtime is 0.0195119380951 s
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
/home/david/Dropbox/Ubuntu/Convex_Optimization/Project/Experiments/3_obj/csv_3_22
